### ISSUE TITLE
Relisten not playing Phish on Sonos

### ISSUE THREAD

**Issue by rockymtnryan** [jcraigk/phishin#191]
I've had Sonos for over a year and never had any issues playing Phish via the Relisten music service on my Sonos app, until recently. Every other band on Relisten will play thru my Sonos system, except for Phish. Any track selected will not play with error "Unable to play (song title)-the connection with Relisten was lost. If I select any other band GD, JRAD, etc everything plays fine. Thought I would post here to see if there's some bug. I can play Phish tracks via Relisten on my mobile device Chrome browser as well as on my laptop with no issue, only problem is trying to play on my Sonos speakers thru the Sonos app. I have Sonos support looking into it as well.

**Comment by jcraigk** [comment]
This is due to the fact that Phish.in began enforcing SSL (`https` addresses on all requests) and the site currently uses CloudFlare as a CDN.  Sonos apparently does not support CloudFlare's SSL setup.  Even using a self-signed cert on the Phish.in server itself does not solve the issue.

I'm asking folks to contact Sonos and encourage them to support CloudFlare's (as I understand it, pretty common) SSL scheme.

**Comment by jcraigk** [comment]
This should now be fixed due to efforts by @alecgorge on the Relisten side of things.  🎉
