### ISSUE TITLE
Replace google maps with free alternative or remove Map feature

### ISSUE THREAD

**Issue by jcraigk** [jcraigk/phishin#229]
Mapbox is probably best option - free up to 50k requests

**Comment by ucpete** [comment]
Heh, I _just_ noticed this wasn't working and came here to make this same issue.

My recommendation, for what it's worth:
1. remove the map functionality entirely, effective immediately
2. replace it with city / state / country matching instead

The only time I ever use location-based searching is when I'm looking for shows played in the _same_ 'place'; like, maybe I want to see all shows played in Spain, or all shows played in Rhode Island, or all shows played in San Francisco, or all shows played at some venue. Not once do I ever think "I want shows played within some distance" of some other landmark. This actually simplifies things, as long as there's some notion of "venues are in cities, cities are in states, states are in countries / provinces" on the backend (with some graceful way to handle Europe and Asia).

Part of the reason I have this expectation about how it works could very well be that that's how the phish.net behavior works - where venues, cities, states, and countries link out to all the shows played there - but I do believe this is the expected behavior for most, regardless of precedent.
