### ISSUE TITLE
Download entire shows in a Zip file

### ISSUE THREAD

**Issue by jamesdaily** [jcraigk/phishin#347]
I prefer to download locally instead of streaming.

It's possible to do this track by track.

It'd be more convenient to be able to download an entire show or set as a Zip file with one click.

**Comment by jamesdaily** [comment]
Possible implementations: 

1. Zip on demand. Benefits: no need to pre-zip nor update zip when tracks change. No need to store zipped shows (which would double storage requirements). Could support dynamic bundling by set or playlist vs just entire show. 
2. Zip ahead of time: Benefits: less compute required over time, easier to cache.

**Comment by jcraigk** [comment]
Playlists/shows as zipfiles was a feature in the initial release but I dropped it because it was inefficient/slow (it was synchronous) and used infrequently. This could be re-added as an async job but it would require adding Sidekiq or other background task processing, which would also require Redis. Due to these requirements I don't think it belongs on the primary roadmap at this time. Downloading tracks by batch could easily be done via the API and in parallel, obviating the need for zipping/unzipping.

If someone wants to take a crack at a browser-based track download feature, I'd be open to that, but at this point I'm hesitant to add it as a backend feature. Frontend implementation would likely be easier if using React, which is started at https://github.com/jcraigk/phishin/pull/325

**Comment by jamesdaily** [comment]
A "download all" button which effectively just triggered downloads of all individual tracks separately would be just fine.

**Comment by jamesdaily** [comment]
Great, thank you!

**Comment by jcraigk** [comment]
👍 Note that it will take about a week for the zipfiles to be generated in the background. The job is going chronologically so if you go back to an early show like https://phish.in/1983-12-02 and click on the show context menu you'll see the option to "Download MP3s".

<img width="476" alt="Screenshot 2024-10-04 at 11 39 40 AM" src="https://github.com/user-attachments/assets/e050acbd-e639-44c1-b40b-8f88dc554462">

**Comment by jcraigk** [comment]
Reopening because I ended up filling up the hard drive with album zipfiles...oops. Will need to implement a system to request an album ZIP and email the user when it's done a few minutes later, then get auto-purged after a period.
